spoonacular_API_KEY=NOOO00000000000000000
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
openai.api.key=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
openai.api.model=gpt-4o-mini
openai.api.url=https://api.openai.com/v1/chat/completions