spring.application.name=myvitalmate
#spoonacular.api.key=MY_API_KEY
#openai.ai.key=MY_OPENAI_API_KEY
#openai.ai.model=gpt-4o-mini
#openai.ai.url=https://api.openai.com/v1/chat/completions
#spring.ai.ollama.chat.options.model=llama3.2
