spring.application.name=myvitalmate
##########################################################################
# Import dev configuration if present
spring.config.import=optional:file:./config/customApplication.properties
##########################################################################
spoonacular.api.key=${SPOONACULAR_API_KEY}
openai.api.key=${OPENAI_API_KEY}
openai.api.model=${OPENAI_API_MODEL:gpt-4o-mini}
openai.api.url=${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL:llama3.2}
##########################################################################
# Database configuration
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/myvitalmatedb}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
##########################################################################
# File upload configuration
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:5MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:5MB}
##########################################################################
# JWT configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
##########################################################################