spring.application.name=myvitalmate
#spoonacular.api.key=MY_API_KEY
#openai.api.key=MY_OPENAI_API_KEY
#openai.api.model=gpt-4o-mini
#openai.api.url=https://api.openai.com/v1/chat/completions
#spring.api.ollama.chat.options.model=llama3.2
